export const OPERATION_LABELS: Record<string, string> = {
  addProduct: 'Agregar producto',
  updateProduct: 'Actualizar producto',
  deleteProduct: 'Eliminar producto',
  addMovement: 'Registrar movimiento',
  addSale: 'Registrar venta',
  addEmployee: 'Agregar empleado',
  cancelTransit: 'Cancelar tránsito',
  registerWasteFromTransit: 'Registrar merma',
  registerManualConsumption: 'Registrar consumo',
  createPendingAccount: 'Crear cuenta pendiente',
  chargePendingAccount: 'Cobrar cuenta pendiente',
  deletePendingAccount: 'Eliminar cuenta pendiente',
  addItemsToPendingAccount: 'Agregar items a cuenta',
  updatePendingAccountItems: 'Actualizar items de cuenta',
  togglePendingAccountType: 'Cambiar tipo de cuenta',
  createDailyClosing: 'Crear cierre de caja',
  addRecipe: 'Agregar receta',
  updateRecipe: 'Actualizar receta',
  deleteRecipe: 'Eliminar receta',
  updatePendingAccount: 'Actualizar cuenta',
  justifyMovement: 'Justificar movimiento',
  updateAccessPinAttempts: 'Actualizar intentos PIN',
  markPendingAccountPaid: 'Marcar cuenta pagada',
  logAction: 'Registrar acción',
};

export const MODULE_LABELS: Record<string, string> = {
  'inventory': 'Inventario',
  'sales': 'Ventas',
  'closings': 'Cierres de Caja',
  'transit': 'Tránsito',
  'recipes': 'Recetas',
  'employees': 'Empleados',
  'departments': 'Departamentos',
  'payroll': 'Nómina',
  'hr': 'RRHH',
  'loans': 'Deducciones',
  'liquidations': 'Liquidaciones',
  'accounts': 'Cuentas Pendientes',
  'sync': 'Sincronización',
  'movements': 'Movimientos',
  'settings': 'Configuración',
  'stock': 'Almacén',
  'action-logs': 'Registro de Acciones',
  'consumption': 'Consumo',
  'filtered': 'Centro Filtrado',
  'analysis': 'Análisis',
  'charts': 'Gráficos',
};

export const ACTION_LABELS: Record<string, string> = {
  'CREAR': 'Crear',
  'ELIMINAR': 'Eliminar',
  'ACTUALIZAR': 'Actualizar',
  'MODIFICAR': 'Modificar',
  'ENTRADA': 'Entrada',
  'SALIDA': 'Salida',
  'MERMA': 'Merma',
  'AJUSTE': 'Ajuste',
  'CANCELAR_TRANSITO': 'Cancelar Tránsito',
  'MERMA_TRANSITO': 'Merma en Tránsito',
  'CONSUMO_MANUAL': 'Consumo Manual',
  'COMPENSAR': 'Compensar Sincronización',
  'AGREGAR_ITEMS': 'Agregar Items',
  'ACTUALIZAR_ITEMS': 'Actualizar Items',
  'TOGGLE_TIPO': 'Cambiar Tipo',
  'MARCAR_PAGADO': 'Marcar Pagado',
  'JUSTIFICAR': 'Justificar',
  'GENERAR_NOMINA': 'Generar Nómina',
  'APLICAR_NOMINA': 'Aplicar Nómina',
  'REABRIR_NOMINA': 'Reabrir Nómina',
  'ACTUALIZAR_NOMINA': 'Actualizar Nómina',
};

export const DETAIL_KEY_TRANSLATIONS: Record<string, string> = {
  product_name: 'Producto',
  quantity: 'Cantidad',
  unit: 'Unidad',
  reason: 'Razón',
  note: 'Nota',
  category: 'Categoría',
  total: 'Total',
  items_count: 'Ítems',
  sale_type: 'Tipo de venta',
  sale_name: 'Nombre de venta',
  employee: 'Empleado',
  is_account_house: 'Cuenta casa',
  client_name: 'Cliente',
  recipe_name: 'Receta',
  recipe_id: 'ID Receta',
  new_price: 'Nuevo precio',
  selling_price: 'Precio de venta',
  ingredients_count: 'Ingredientes',
  ingrediente_anterior: 'Ingrediente anterior',
  ingrediente_nuevo: 'Nuevo ingrediente',
  doc_type: 'Tipo doc.',
  file_name: 'Archivo',
  doc_name: 'Documento',
  changes: 'Cambios',
  closing_date: 'Fecha de cierre',
  total_sales: 'Ventas totales',
  total_discounts: 'Descuentos',
  total_refunds: 'Devoluciones',
  closing_amount: 'Monto del cierre',
  created_by_name: 'Cerrado por',
  month: 'Mes',
  year: 'Año',
  total_employees: 'Total empleados',
  total_net: 'Neto total',
  employee_name: 'Empleado',
  field: 'Campo',
  old_value: 'Valor anterior',
  new_value: 'Nuevo valor',
  old_quantity: 'Cantidad anterior',
  new_quantity: 'Nueva cantidad',
  earned_salary: 'Salario devengado',
  base_salary: 'Salario básico',
  vacation_days: 'Días de vacación',
  exemption_base: 'Base exenta',
  taxable_base: 'Base imponible',
  tax_amount: 'Impuesto',
  special_contribution: 'Contribución especial',
  net_salary: 'Salario neto',
  salary: 'Salario',
  justification: 'Justificación',
  payment_method: 'Método de pago',
  product_id: 'ID Producto',
  productId: 'ID Producto',
  name: 'Nombre',
  sale_id: 'ID Venta',
  transitItemId: 'ID Tránsito',
  customer: 'Cliente',
  account_id: 'ID Cuenta',
  accountId: 'ID Cuenta',
  id: 'ID',
  type: 'Tipo',
  date: 'Fecha',
  customer_name: 'Cliente',
  count: 'Cantidad',
  recovered: 'Recuperados',
  failed: 'Fallidos',
  cost: 'Costo',
  rop: 'Punto de reorden',
  eoq: 'Cant. econ. pedido',
  price: 'Precio',
  in_transit: 'En tránsito',
  updated_at: 'Actualizado en',
  is_individual: 'Es individual',
  is_consumo_directo: 'Consumo directo',
  is_gasto_variable: 'Gasto variable',
  lead_time: 'Tiempo de entrega',
  order_cost: 'Costo de pedido',
  holding_cost: 'Costo almacen.',
  expiration_date: 'Fecha expiración',
  description: 'Descripción',
  is_active: 'Activo',
  address: 'Dirección',
  businessHours: 'Horario',
  businessName: 'Nombre del negocio',
  businessCode: 'Código de negocio',
  generateTicket: 'Generar ticket',
  ticketMessage: 'Mensaje del ticket',
  phone: 'Teléfono',
};
